In [5]:
import numpy as np
import pandas as pd

In [6]:
pd.__version__

'3.0.2'

In [7]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in c:\users\pc 27\anaconda3\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc 27\anaconda3\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc 27\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pc 27\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\pc 27\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

### create a series

In [9]:
list=[10,20,30,40,50]
s1=pd.Series(list)
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
# if guna numpy nk convert to pandas 

narr=np.array([10,20,30,40,50])
s2=pd.Series(narr)
print(s2)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [11]:
# dictionary 

dict={'a':10, 'b':20, 'c':30, 'd':40, 'e':50}
s3=pd.Series(dict)
print(s3)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [12]:
list=[10,20,30,40,50]
label=['a','b','c','d','e']
s1=pd.Series(list,index=label)
print(s1)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [13]:
s3.dtype

dtype('int64')

In [14]:
s3.size

5

In [15]:
# convert int to float
s3.astype(float)

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
dtype: float64

In [16]:
s3.drop('b')

a    10
c    30
d    40
e    50
dtype: int64

### create dataframe

In [18]:
list=[ [1,2], [3,4], [5,6] ]
df1=pd.DataFrame(list,index=['a','b','c'],columns=['col1','col2'])

#index untuk nama row 
#columns untuk nama col 

print(df1)

# dataframe = 2D array

   col1  col2
a     1     2
b     3     4
c     5     6

In [19]:
#if use numpy

ndarr=np.array([ [1,2], [3,4], [5,6] ])
df1=pd.DataFrame(ndarr,index=['a','b','c'],columns=['col1','col2'])

#index untuk nama row 
#columns untuk nama col 

print(df1)

# dataframe = 2D array

   col1  col2
a     1     2
b     3     4
c     5     6

In [20]:
# from dictionary :

In [21]:
pd.DataFrame({'R1':[1,2,3],'R2':[4,5,6]})

   R1  R2
0   1   4
1   2   5
2   3   6

In [22]:
df2=pd.DataFrame({'R1':[1,2,3],'R2':[4,5,6]}, index=['a','b','c'])
print(df2)

   R1  R2
a   1   4
b   2   5
c   3   6

In [23]:
df2.dtypes

R1    int64
R2    int64
dtype: object

In [24]:
df2.info()

<class 'pandas.DataFrame'>
Index: 3 entries, a to c
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   R1      3 non-null      int64
 1   R2      3 non-null      int64
dtypes: int64(2)
memory usage: 72.0+ bytes

In [25]:
df2['R1'].dtype

dtype('int64')

In [26]:
df2.shape

(3, 2)

In [27]:
df2.head(1)

   R1  R2
a   1   4

In [28]:
df2.tail(1)

   R1  R2
c   3   6

In [29]:
df2.drop('R1',axis=1)

   R2
a   4
b   5
c   6

In [30]:
df2.drop('b',axis=0)

   R1  R2
a   1   4
c   3   6

### Indexing data in a series

In [32]:
dict={'a':10, 'b':20, 'c':30, 'd':40, 'e':50}
s3=pd.Series(dict)
print(s3)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [33]:
s3['b']

np.int64(20)

In [34]:
s3.iloc[1]

# if tk guna iloc, kena buat mcm atas

np.int64(20)

In [35]:
s3[['a','c']]

a    10
c    30
dtype: int64

In [36]:
s3>20

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [37]:
list=[ [1,2], [3,4], [5,6] ]
df1=pd.DataFrame(list,index=['a','b','c'],columns=['col1','col2'])
print(df1)

   col1  col2
a     1     2
b     3     4
c     5     6

In [38]:
df1['col1']

a    1
b    3
c    5
Name: col1, dtype: int64

In [39]:
df1[['col1','col2']]

   col1  col2
a     1     2
b     3     4
c     5     6

In [40]:
df1.iloc[2]

col1    5
col2    6
Name: c, dtype: int64

In [41]:
df1

   col1  col2
a     1     2
b     3     4
c     5     6

In [42]:
# to access number 4

df1.iloc[1,1]

np.int64(4)

In [43]:
# Exercise 

sales=pd.DataFrame({'Month':['Jan','Feb','Mar','Apr','May','June'],
                   'Revenue':[50000, 55000, 48000, 62000, 58000, 61000],
                   'Expenses':[35000,38000,34000,41000,39000,40000]},index=['a','b','c','d','e','f'])

In [44]:
sales

  Month  Revenue  Expenses
a   Jan    50000     35000
b   Feb    55000     38000
c   Mar    48000     34000
d   Apr    62000     41000
e   May    58000     39000
f  June    61000     40000

In [45]:
#Find the first 2 row of the data (month,revenue,expenses)
#Find the first 3 months of Revenue
#Find the last 2 months of Expenses

In [46]:
#Find the first 2 row of the data (month,revenue,expenses)

sales.head(2)

  Month  Revenue  Expenses
a   Jan    50000     35000
b   Feb    55000     38000

In [47]:
#Find the first 3 months of Revenue

sales['Revenue'].iloc[:3]

a    50000
b    55000
c    48000
Name: Revenue, dtype: int64

In [48]:
#Find the last 2 months of Expenses

sales['Expenses'].iloc[4:]

e    39000
f    40000
Name: Expenses, dtype: int64

In [52]:
sales.iloc[2,2]

np.int64(34000)

In [54]:
profit = sales['Revenue']-sales['Expenses']
profit

a    15000
b    17000
c    14000
d    21000
e    19000
f    21000
dtype: int64

In [62]:
sales['Revenue']*2

a    100000
b    110000
c     96000
d    124000
e    116000
f    122000
Name: Revenue, dtype: int64

In [64]:
print(sales)
print(profit)

  Month  Revenue  Expenses
a   Jan    50000     35000
b   Feb    55000     38000
c   Mar    48000     34000
d   Apr    62000     41000
e   May    58000     39000
f  June    61000     40000
a    15000
b    17000
c    14000
d    21000
e    19000
f    21000
dtype: int64

In [70]:
sales['Profit']= sales['Revenue']-sales['Expenses']
print(sales)

  Month  Revenue  Expenses  Profit
a   Jan    50000     35000   15000
b   Feb    55000     38000   17000
c   Mar    48000     34000   14000
d   Apr    62000     41000   21000
e   May    58000     39000   19000
f  June    61000     40000   21000

In [84]:
profit*sales[['Expenses','Revenue']]

   Expenses  Revenue   a   b   c   d   e   f
a       NaN      NaN NaN NaN NaN NaN NaN NaN
b       NaN      NaN NaN NaN NaN NaN NaN NaN
c       NaN      NaN NaN NaN NaN NaN NaN NaN
d       NaN      NaN NaN NaN NaN NaN NaN NaN
e       NaN      NaN NaN NaN NaN NaN NaN NaN
f       NaN      NaN NaN NaN NaN NaN NaN NaN

In [86]:
data={'A':[1,2,3],'B':[4,5,6],'A':[7,8,9]}
df=pd.DataFrame(data)
df

   A  B
0  7  4
1  8  5
2  9  6

In [90]:
data={'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
df=pd.DataFrame(data,index=['a','b','a'])
df

   A  B  C
a  1  4  7
b  2  5  8
a  3  6  9

In [92]:
df.loc['a']

   A  B  C
a  1  4  7
a  3  6  9

In [94]:
df.loc['b']

A    2
B    5
C    8
Name: b, dtype: int64

In [100]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
df=pd.DataFrame(arr,columns=['A','B','A'])
df

   A  B  A
0  1  2  3
1  4  5  6
2  7  8  9

In [102]:
df['A']

   A  A
0  1  3
1  4  6
2  7  9

In [104]:
df.describe()

         A    B    A
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [110]:
df.mean()

A    4.0
B    5.0
A    6.0
dtype: float64

In [112]:
df.median()

A    4.0
B    5.0
A    6.0
dtype: float64

In [116]:
df['B'].mode()

0    2
1    5
2    8
Name: B, dtype: int64

In [126]:
arr1=np.array([[1,2,3],[2,8,6],[2,8,8]])
df1=pd.DataFrame(arr1,columns=['A','B','A'])
df1.mode()

     A    B  A
0  2.0  8.0  3
1  NaN  NaN  6
2  NaN  NaN  8

In [128]:
df.count()

A    3
B    3
A    3
dtype: int64

In [132]:
df1['B'].unique()

array([2, 8])

In [134]:
df=df1

In [140]:
#Function Application and Mapping
series=pd.Series([1,2,3,4,5])

np.square(series)

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [144]:
dict={'A':[1,2,3],'B':[4,5,6]}
df=pd.DataFrame(dict)
np.square(df)

   A   B
0  1  16
1  4  25
2  9  36

In [150]:
series=pd.Series([1,2,3,4,5])
series.apply(np.sqrt) #same as np.sqrt(series)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
dtype: float64

In [154]:
def categorize(x):
    if x>=5:
        return 'high'
    else:
        return 'low'

In [156]:
df['B'].apply(categorize)

0     low
1    high
2    high
Name: B, dtype: str

In [164]:
df.apply(sum,axis=0)

A     6
B    15
dtype: int64

In [ ]:
dict={'A':[1,2,3],'B':[4,5,6]}
df=pd.DataFrame(dict)
np.square(df)

In [166]:
df=pd.DataFrame({'month':['Jan','Feb','Mar','Ápr'],
                 'rev':[230,300,400,500]})
df

  month  rev
0   Jan  230
1   Feb  300
2   Mar  400
3   Ápr  500

In [ ]:
df['month'].map({'Jan':})

In [168]:
#Pivot Table

In [170]:
data={
    'City':['KL','Selangor','Ipoh','Kuching'],
    'Category':['A','A','B','B'],
    'Sales':[2000,3000,4000,5000]
}
df=pd.DataFrame(data)
df

       City Category  Sales
0        KL        A   2000
1  Selangor        A   3000
2      Ipoh        B   4000
3   Kuching        B   5000

In [186]:
pd.pivot_table(df,values='Sales',columns='City',index='Category')

City        Ipoh      KL  Kuching  Selangor
Category
A            NaN  2000.0      NaN    3000.0
B         4000.0     NaN   5000.0       NaN

In [188]:
pd.pivot_table(df,values='Sales',columns='City',index='Category',aggfunc='sum')

City        Ipoh      KL  Kuching  Selangor
Category
A            NaN  2000.0      NaN    3000.0
B         4000.0     NaN   5000.0       NaN

In [190]:
pd.crosstab(df,index='City',columns='Category')

TypeError: crosstab() got multiple values for argument 'index'

In [192]:
pd.crosstab(df['City'],df['Category'])

Category  A  B
City
Ipoh      0  1
KL        1  0
Kuching   0  1
Selangor  1  0

In [196]:
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})

#create a view
view=df['A']

#modify the view
view[0]=9999

print(df)
print(view)

   A  B
0  1  4
1  2  5
2  3  6
0    9999
1       2
2       3
Name: A, dtype: int64